services:
  db:
    environment:
      MYSQL_DATABASE: "magento2_${_M2D_MAGE_SHORT_VERSION}"
    container_name: "m2devbox-${_M2D_MAGE_SHORT_VERSION}-db"

  web:
    container_name: "m2devbox-${_M2D_MAGE_SHORT_VERSION}-web"
    build:
      context: ./php/${_M2D_DOCKER_PHP_IMG_VERSION}
    depends_on:
      - elastic
      - db
      - redis
    volumes:
      - "${_M2D_MAGE_SRC_DIR}:/var/www/html:cached"
      - "${_M2D_APP_CODE_DIR}:/var/www/html/app/code:cached"

  elastic:
    container_name: "m2devbox-${_M2D_MAGE_SHORT_VERSION}-elastic"
    build:
      context: ./elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-elastic:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - "${M2D_ES_PORT}:9200"
      - "${M2D_ES_CONTROL_PORT}:9300"
    networks:
      - m2dnet

  redis:
    container_name: "m2devbox-${_M2D_MAGE_SHORT_VERSION}-redis"

volumes:
  data-elastic:
    driver: local
