services:
  db:
    environment:
      MYSQL_DATABASE: "magento2_${MAGE_SHORT_VERSION}"
    container_name: "mage2devbox-${MAGE_SHORT_VERSION}-db"
    networks:
      - elastic

  web:
    container_name: "mage2devbox-${MAGE_SHORT_VERSION}-web"
    build:
      context: ./php/${PHP_IMG_VERSION}
    depends_on:
      - elastic
      - db
    volumes:
      - "${MAGE_SRC}:/var/www/html:cached"
      - "${APP_CODE}:/var/www/html/app/code:cached"
    networks:
      - elastic

  elastic:
    container_name: "mage2devbox-${MAGE_SHORT_VERSION}-elastic"
    build:
      context: ./elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-elastic:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - "${DOCKER_ES_PORT}:9200"
      - "${DOCKER_ES_CONTROL_PORT}:9300"
    networks:
      - elastic

volumes:
  data-elastic:
    driver: local

networks:
  elastic:
    driver: bridge
