version: '3'

services:
  db:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: "magento2"
      MYSQL_PASSWORD: "magento2"
      MYSQL_ROOT_HOST: "%"
    expose:
      - 3306
    ports:
      - "${DOCKER_DB_PORT}:3306"

  web:
    build:
      args:
        TIMEZONE: "${TIMEZONE}"
    depends_on:
      - db
    ports:
      - "${DOCKER_WEB_PORT}:80"
    stdin_open: true
    tty: true
    volumes:
      - ${COMPOSER_CACHE:-/var/www/.composer}:/var/www/.composer:cached
      - ${COMPOSER_AUTH:-/var/www/composer/auth.json}:/var/www/.composer/auth.json:cached
