#!/usr/bin/env php
<?php

/**
 * Mage2 Devbox
 */

use Devbox\Devbox;
use Devbox\Service\Config;
use Dotenv\Dotenv;

$cwd = getcwd();

define('CWD', $cwd);
define('DB_ROOT', __DIR__);

require DB_ROOT.'/vendor/autoload.php';

define('DB_SRC', __DIR__.'/src');
define('DB_VERSION', '0.1');
define('DOCKER_CONFIGS', __DIR__.'/docker');

// load default ENV vars form config
$defaultEnv = Config::get('default_env');
foreach ($defaultEnv as $key => $value) {
    if (!empty($value) && !array_key_exists($key, $_ENV)) {
        $_ENV[$key] = $value;
        putenv($key.'='.$value);
    }
}

// load custom ENV vars from $CWD/.env
$dotenv = Dotenv::createMutable(CWD);
$dotenv->load();

// init and run application
$devbox = new Devbox('Mage2 Devbox', DB_VERSION);

/** @noinspection PhpUnhandledExceptionInspection */
$devbox->run();
