#!/usr/bin/env php
<?php

/**
 * Mage2 Devbox
 */

use Devbox\Devbox;
use Devbox\Service\Config;
use Dotenv\Dotenv;

define('DB_ROOT', __DIR__);

require DB_ROOT.'/vendor/autoload.php';

define('DB_SRC', __DIR__.'/src');
define('DB_VERSION', '0.1');
define('DOCKER_CONFIGS', __DIR__.'/docker');

// make sure that a .env for Docker compose exists
Config::ensureDockerEnv();

// load .env variables into $_ENV
$dotenv = Dotenv::createImmutable(Config::getConfigDir(), [Config::getDockerEnvFilename()]);
$dotenv->load();

// init and run application
$devbox = new Devbox('Mage2 Devbox', DB_VERSION);

/** @noinspection PhpUnhandledExceptionInspection */
$devbox->run();
